node_search:
  path: node
  search: 0
  advanced:
    visibility: 0
    collapsible: 1
    collapsed: 1
    criteria:
      or: or
      phrase: phrase
      negative: negative
    types:
      about: about
      award: award
      book: book
      collaborator: collaborator
      credit: credit
      embedded_video: embedded_video
      event: event
      idea: idea
      image_set: image_set
      job: job
      manifesto: manifesto
      press: press
      profile: profile
      task: task
    languages:
      en: en
      zh-hans: zh-hans
      und: und
      zxx: zxx
  info:
    type: type
    user: 0
    date: 0
  filter:
    position: disabled
    label: 'Filter the results'
    any: '- Any -'
